### ISSUE TITLE
Console Window

### ISSUE THREAD

**Issue by julot** [uyjulian/Translation-Aggregator#20]
Please remove/hide the console window.

**Comment by uyjulian** [comment]
This will be fixed in the next release.

**Comment by shinigamichan** [comment]
A console window still pops up in release [v1.0.4](https://github.com/uyjulian/Translation-Aggregator/releases/tag/v1.0.4). What's needed to prevent a console window from popping up is a `-Wl,--subsystem,windows` in LDFLAGS (I tested after replacing i686 in the makefile with x86_64 since that was what I had installed).
